name: Auto approve and merge PR
on: workflow_dispatch
      
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            # const activeBranches = ['feature/staging', 'feature/qa'];
            const prIds = []

            const pulls = await github.rest.pulls.pulls({
              title: `Master -> ${branch}`,
              owner,
              repo,             
            }) 
            console.log(pulls)

